apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-tools
  namespace: 14hw
spec:
  selector:
    matchLabels:
      app: nettools
  replicas: 3
  template:
    metadata:
      labels:
        app: nettools
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.4
        ports:
        - containerPort: 80
      - name: multitool
        image: wbitt/network-multitool
        ports:
        - containerPort: 8080
        env: 
          - name: HTTP_PORT
            value: "1180"
---

apiVersion: v1
kind: Service
metadata:
  name: network-service
  namespace: 14hw
spec:
  selector:
    app: nettools
  ports:
    - protocol: TCP
      name: nginx
      port: 9001
      targetPort: 80
    - protocol: TCP
      name: multitool
      port: 9002
      targetPort: 1180
---

apiVersion: v1
kind: Pod
metadata:
  name: multitool
  namespace: 14hw
spec:
  containers:
    - name: multitool
      image: wbitt/network-multitool
      ports:
        - containerPort: 8080